# This file is a template, and might need editing before it works on your project.
# Official docker image.

build:
  image: docker:17.05.0
  #image: dgcr.io/google-containers/kube-cross:v1.8.1-2
  stage: build
  script:
    - ./build/run.sh make || sleep 999999
    - echo time to login to the runner
    - sleep 99999999
